media:
  input: static/media
  output: /media

content:
  - name: site-settings
    label: Site settings
    path: src/lib/site/settings.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
      - name: logo
        label: Site logo
        type: image