media:
  input: static/media
  output: /media

content:
  
  - name: home-page
    label: Home page
    path: src/lib/site/home.json
    type: file
    fields:
      - name: hero_title
        label: Homepage title
        type: string
        required: true
      - name: hero_description
        label: Homepage description
        type: string
        required: true
      - name: hero_cover
        label: Cover image
        type: image
        required: true
      - name: introduction
        label: Introduction
        type: rich-text
      - name: features
        label: Features
        type: object
        fields:
          - name: emoji
            label: Emoji
            type: string
            required: true
          - name: title
            label: Feature title
            type: string
            required: true
          - name: description
            label: Feature description
            type: string
            required: true

  - name: site-settings
    label: Site settings
    path: src/lib/site/settings.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
        required: true
      - name: description
        label: Website description
        type: string
      - name: logo
        label: Site logo
        type: image